os: linux
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8

before_install:
- pip install --upgrade pip
- pip install poetry
install:
- poetry install -v
- pip install --upgrade tox-travis
script: tox

before_deploy:
- pip install --upgrade pip
- pip install poetry
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    python: 3.8
