os: linux
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8

before_install:
- pip install --upgrade pip
- pip install --upgrade tox tox-travis
#we don't need it, since tox itself will do poetry install
#- poetry install -v
script: tox

before_deploy:
- pip install --upgrade pip
- pip install poetry==1.0.0b3
deploy:
  provider: script
  script:
  - poetry publish --build --username ${PYPI_USER} --password ${PYPI_PASSWORD}
  on:
    tags: true
    python: 3.8
